### ISSUE TITLE
Time matching too greedy

### ISSUE THREAD

**Issue by grobie** [caarlos0/vscode-prometheus-language#1]
Thanks for this extension!

I noticed the time matching is too greedy, and will colorize anything which looks like a time (e.g. `8s`) anywhere in the text, including words like `K8s` for Kubernetes.

![screenshot from 2018-09-17 13-37-49](https://user-images.githubusercontent.com/3432/45621035-35248980-ba7f-11e8-9f2f-55581bdd183b.png)

I suggest to only apply the regexp on `FOR`/`for` values and directly inside of range vectors (e.g. `my_metric_name[8s]`).

**Comment by caarlos0** [comment]
yeah, the syntax is ported from https://github.com/Zevran/language-prometheus

also the .rules thing is outdated anyway :P 

<blockquote><img src="https://avatars2.githubusercontent.com/u/498465?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/Zevran/language-prometheus">Zevran/language-prometheus</a></strong></div><div>Prometheus Alert language support in Atom. Contribute to Zevran/language-prometheus development by creating an account on GitHub.</div></blockquote>
